'use client';

import { useState } from 'react';
import Link from 'next/link';
import { motion } from 'framer-motion';

const API = 'http://localhost:3000';

export default function ForgotPasswordPage() {
  const [identifier,setIdentifier]=useState(''); const [message,setMessage]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
  async function handleSubmit(e:React.FormEvent){e.preventDefault();setError('');setMessage('');setLoading(true);try{const res=await fetch(`${API}/auth/forgot-password`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({identifier})});const data=await res.json();if(!res.ok)throw new Error(data.message||'Something went wrong');setMessage(data.message)}catch(err){setError(err instanceof Error?err.message:'Something went wrong')}finally{setLoading(false)}}
  return <main className="relative min-h-screen overflow-hidden bg-[#f7f8fc] p-5 sm:p-8"><div className="absolute -left-32 -top-32 h-96 w-96 rounded-full bg-teal-300/20 blur-[100px]"/><div className="absolute -bottom-40 -right-32 h-[28rem] w-[28rem] rounded-full bg-indigo-300/20 blur-[110px]"/>
    <div className="relative mx-auto flex min-h-[calc(100vh-2.5rem)] max-w-6xl items-center justify-center"><motion.div initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} className="grid w-full overflow-hidden rounded-[32px] border border-white bg-white/80 shadow-[0_35px_100px_-40px_rgba(15,23,42,.3)] backdrop-blur-xl lg:grid-cols-[.9fr_1.1fr]">
      <section className="hidden bg-[#0b1020] p-10 text-white lg:flex lg:flex-col lg:justify-between"><div><Link href="/" className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-white text-slate-950 font-black">S</span><span className="text-xl font-black">Skilho</span></Link><div className="mt-24"><div className="mb-5 text-4xl">🔐</div><h1 className="text-4xl font-black tracking-tight">Get back to<br/><span className="text-teal-300">your workspace.</span></h1><p className="mt-5 max-w-sm text-sm leading-7 text-white/50">No worries. Enter the email or mobile number connected to your account and we’ll help you reset your password.</p></div></div><p className="text-xs text-white/30">Secure account recovery · Skilho</p></section>
      <section className="p-7 sm:p-10 lg:p-14"><Link href="/" className="text-sm font-bold text-slate-400 hover:text-slate-700">← Skilho</Link><div className="mx-auto mt-12 max-w-md"><span className="inline-flex rounded-full bg-teal-50 px-3 py-1.5 text-xs font-bold text-teal-700">ACCOUNT RECOVERY</span><h2 className="mt-4 text-4xl font-black tracking-[-.04em]">Forgot your password?</h2><p className="mt-3 text-sm leading-6 text-slate-500">We’ll send instructions to the contact details associated with your Skilho account.</p><form onSubmit={handleSubmit} className="mt-8 space-y-5"><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[.08em] text-slate-500">Email or mobile number</span><input value={identifier} onChange={e=>setIdentifier(e.target.value)} required placeholder="you@example.com" className="modern-forgot-input"/></label>{error&&<div className="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-medium text-red-700">{error}</div>}{message&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-700">{message}</div>}<button disabled={loading} className="w-full rounded-2xl bg-gradient-to-r from-teal-600 to-blue-600 py-3.5 text-sm font-bold text-white shadow-lg shadow-teal-600/20 disabled:opacity-60">{loading?'Sending...':'Send reset link'}</button></form><p className="mt-7 text-center text-sm text-slate-500">Remembered it? <Link href="/login/technician" className="font-bold text-teal-700">Back to sign in</Link></p></div></section>
    </motion.div></div><style jsx global>{`.modern-forgot-input{width:100%;border:1px solid #e2e8f0;background:#f8fafc;border-radius:16px;padding:14px 15px;outline:none;transition:.2s}.modern-forgot-input:focus{background:#fff;border-color:#0d9488;box-shadow:0 0 0 4px rgba(13,148,136,.1)}`}</style></main>
}
